In [134]:
#1
import numpy as np

In [135]:
#2
zerosArray = np.zeros(10)
print(*zerosArray)

0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0


In [136]:
#3
zerosArrayWithOne = np.zeros(10)
zerosArrayWithOne[9] = 1
print(*zerosArrayWithOne)

0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0


In [137]:
#4
tenToFortynineArray = np.arange(10,50)
print(*tenToFortynineArray)

10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49


In [138]:
#5
rangeZeroNine = np.arange(0,9)
ThreeByThree = rangeZeroNine.reshape(3,3)
print(ThreeByThree)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [171]:
#6
# boolean filtering
array1=np.array([1,2,0,0,4,0])
array1NoZerosBoolean = (array1 != 0)
array1NoZeros = array1[array1Boolean]
print(array1NoZeros)
# nonzero ***
array1NoZeros = np.nonzero(array1)
print(array1[array1NoZeros])

[1 2 4]
[1 2 4]


In [140]:
#7
ThreeByThreeIdentityMatrix = np.eye(3,3)
print(ThreeByThreeIdentityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [170]:
#8
ThreeByThreeByThree = np.random.random((3,3,3))
print(ThreeByThreeByThree)

[[[0.47739229 0.39314821 0.37583092]
  [0.27161299 0.14358299 0.29819898]
  [0.75095396 0.64320303 0.13562584]]

 [[0.58423789 0.54431434 0.99220165]
  [0.98474091 0.89716945 0.32313859]
  [0.07810268 0.66804202 0.03958686]]

 [[0.31330283 0.19262647 0.03701916]
  [0.3092953  0.99175298 0.41925115]
  [0.17134942 0.88402019 0.41951231]]]


In [142]:
#9
TenByTen = np.random.random((10,10))
minNumber = TenByTen.min()
maxNumber = TenByTen.max()
print(minNumber)
print(maxNumber)

0.0043778737631485765
0.9976685118486582


In [143]:
#10
RandomVectorThirty = np.random.random((30))
meanVectorThirty = RandomVectorThirty.mean()
print(meanVectorThirty)

0.43318502972256623


In [144]:
#11
arrayFive = np.arange(1,5)
arrayFiveDiagonal = np.diag(arrayFive)
print(arrayFiveDiagonal)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [145]:
#12
fiveByFive = np.random.random((5,5))
normFiveByFive = ((fiveByFive)-(np.mean(fiveByFive)))/((np.std(fiveByFive)))
print(normFiveByFive)

[[ 0.01530485  0.72835145 -0.89761357 -1.26060541  0.29118235]
 [-0.11614915 -0.76091671 -1.37813851  1.38804501 -0.67162254]
 [ 1.53787049 -0.85531974 -0.82450746  1.79163725 -0.1581043 ]
 [-1.72524776  1.16450311 -0.71785225 -0.10425182  0.079891  ]
 [ 1.49716617  0.9983882  -1.11623615  0.26363826  0.83058723]]


In [146]:
#13
array2_1 = np.random.randint(0,10,10)
array2_2 = np.random.randint(0,10,10)
array1And2Intersection = np.intersect1d(array2_1,array2_2)
print(array1And2Intersection)

[3 5 7 8 9]


In [147]:
#14
randomArrayTen1 = np.random.random((10))
randomArrayTen1Sorted = np.sort(randomArrayTen1)
print(randomArrayTen1Sorted)

[0.03693188 0.2299535  0.44392476 0.45331651 0.51870428 0.59585959
 0.64240626 0.78945955 0.81829581 0.90747447]


In [177]:
#15
randomArrayTen2 = np.random.random((10))
print("index of max value " + str(np.argmax(randomArrayTen2)))
randomArrayTen2[np.argmax(randomArrayTen2)] = 0
print(randomArrayTen2)

index of max value 6
[0.39030379 0.71037632 0.12080084 0.18937814 0.34463382 0.43810367
 0.         0.36696175 0.84942067 0.58853105]


In [181]:
#16
randomThreeByThree = np.random.randint(0,10,(3,3))
print(randomThreeByThree)
meansByRow = np.mean(randomThreeByThree, keepdims=True, axis=1)
print(meansByRow)
#stackedMeans = np.vstack((meansByRow, meansByRow, meansByRow))
#print(stackedMeans)
#stackedMeansT = stackedMeans.T
#print(stackedMeansT)
print(randomThreeByThree - meansByRow)

[[8 3 2]
 [1 7 1]
 [1 7 3]]
[[4.33333333]
 [3.        ]
 [3.66666667]]
[[ 3.66666667 -1.33333333 -2.33333333]
 [-2.          4.         -2.        ]
 [-2.66666667  3.33333333 -0.66666667]]


In [185]:
# 17
largeArray = np.random.randint(1,1000,(1,1000))
sortedLargeArray = np.sort(largeArray)
#print(sortedLargeArray)
print(sortedLargeArray[0,-5])
print(sortedLargeArray[0,-5:])

995
[995 995 995 997 999]


In [186]:
#18
threeByFiveArray = np.random.randint(1,10,(5,3))
print(threeByFiveArray)
threeByFiveArrayConditional = np.where(threeByFiveArray>4,threeByFiveArray**2,threeByFiveArray)
print(threeByFiveArrayConditional)

[[3 9 4]
 [3 4 3]
 [5 4 8]
 [6 9 3]
 [9 6 6]]
[[ 3 81  4]
 [ 3  4  3]
 [25  4 64]
 [36 81  3]
 [81 36 36]]
